#
# Install NEOS dependencies
#
RUN apk add --no-cache \
		libpq \
		imagemagick \
	&& apk add --no-cache --virtual .neos-deps \
		$PHPIZE_DEPS \
		imagemagick-dev \
		postgresql-dev \
		openldap-dev \
	&& docker-php-ext-install pdo_pgsql \
	&& docker-php-ext-install ldap \
	&& pecl install imagick \
	&& docker-php-ext-enable imagick \
	&& apk del .neos-deps
