#
# Install TYPO3 dependencies
#
RUN apk add --no-cache \
		imagemagick \
	&& apk add --no-cache --virtual .typo3-deps \
		$PHPIZE_DEPS \
		imagemagick-dev \
	&& docker-php-ext-install pdo_mysql \
	&& docker-php-ext-enable imagemagick \
	&& apk del .typo3-deps
