#
# Install Shopware 6 dependencies
#
RUN apk add --no-cache \
		imagemagick \
	&& apk add --no-cache --virtual .shopware-deps \
		$PHPIZE_DEPS \
		imagemagick-dev \
	&& docker-php-ext-install pdo_mysql \
	&& pecl install imagick \
	&& docker-php-ext-enable imagick \
	&& apk del .shopware-deps
