#
# Install Cockpit dependencies
#
RUN apk add --no-cache \
		imagemagick \
	&& apk add --no-cache --virtual .cockpit-deps \
		$PHPIZE_DEPS \
		openssl-dev \
		imagemagick-dev \
	&& pecl install imagick \
	&& pecl install mongodb \
	&& docker-php-ext-enable imagick \
	&& docker-php-ext-enable mongodb \
	&& apk del .cockpit-deps
